#!/bin/bash

install-file()
{
    mkdir -p `dirname $2`
    ln -sfv $(pwd)/$1 $2
}

install-directory()
{
    ln -sfvT $(pwd)/$1 $2
}

install-target()
{
    echo -e "\033[32mInstalling target \033[34m$1\033[0m"
    case $1 in
        nvim)
            # neovim
            install-directory nvim ~/.config/nvim
            mkdir -pv nvim/{colors,autoload}
            ln -sfv $(pwd)/third_party/vim-plug/plug.vim nvim/autoload
            ln -sfv $(pwd)/third_party/codefocus-vim/colors/codefocus.vim nvim/colors
            ;;
        mutt)
            gpg -d mutt/99-savehooks.muttrc.gpg > mutt/99-savehooks.muttrc
            install-directory mutt/ ~/.mutt
            install-file mailcap ~/.mailcap
            install-file offlineimap/offlineimap.py ~/.offlineimap.py
            install-file offlineimap/offlineimaprc ~/.offlineimaprc
            install-file msmtprc ~/.msmtprc
            install-file bin/imapd ~/bin/imapd
            ;;
        git)
            install-file bin/git-remotify ~/bin/git-remotify
            install-file gitconfig ~/.gitconfig
            ;;
        mpd)
            install-file bin/mpdhosttoggle ~/bin/mpdhosttoggle
            install-file bin/mpcctl ~/bin/mpcctl
            ;;
        mpc)
            install-file bin/currentlyplayed ~/bin/currentlyplayed
            install-file bin/mpvctl ~/bin/mpvctl
            install-file mpv_config ~/.mpv/config
            ;;
        zsh)
            install-file zshrc ~/.zshrc
            install-directory zsh ~/.zsh
            install-directory third_party/z/z.sh ~/.zsh/z.sh
            install-directory third_party/zsh-autoenv/ ~/.zsh/zsh-autoenv
            ;;
        office)
            gpg -d vdirsyncerconfig.gpg > vdirsyncerconfig
            install-file vdirsyncerconfig ~/.vdirsyncer/config
            install-file khalconfig ~/.config/khal/config
            install-file taskrc ~/.taskrc
            install-directory taskwarrior_hooks ~/.task/hooks
            ;;
        i3)
            install-directory polybar/ ~/.config/polybar
            install-directory rofi/ ~/.config/rofi
            install-file bin/i3exit ~/bin/i3exit
            install-file bin/i3status-feeder.pl ~/bin/i3status-feeder.pl
            install-file i3config ~/.config/i3/config
            install-file bin/getpass ~/bin/getpass
            install-file compton.conf ~/.compton.conf
            ;;
        tmux)
            install-file tmuxconf ~/.tmux.conf
            ;;
        misc)
            install-file Xresources ~/.Xresources
            install-file bin/autolatex ~/bin/autolatex
            install-file bin/build-cmake-project ~/bin/build-cmake-project
            install-file bin/start-latex-project ~/bin/start-latex-project
            install-file dunstrc ~/.config/dunst/dunstrc
            install-file gpg-agent.conf ~/.gnupg/gpg-agent.conf
            install-file xinitrc ~/.xinitrc
            install-file termiteconfig ~/.config/termite/config
            install-file zathurarc ~/.config/zathura/zathurarc
            ;;
        ranger)
            mkdir -pv ~/.config/ranger
            for f in `ls rangerconf`
            do
                ln -sfv $(pwd)/rangerconf/$f ~/.config/ranger/
            done
            ;;
        *)
            echo "No such target: $1"
            ;;
    esac
    echo
}

ALLTARGETS="git i3 misc mpc mpd mutt nvim office ranger tmux zsh"
# if no args: install full
if [ $# -eq 0 ]
then
    targets=$ALLTARGETS
    echo -e "Usage: $0 [target-names ...]\n   or  $0 all to install all targets\n\nPossible targets:"
    for target in $targets
    do
        echo -e "\t$target"
    done
    exit 1
else
    if [ "$1" = "all" ]
    then
        targets=$ALLTARGETS
    else
        targets=$@
    fi
fi

for target in $targets
do
    install-target $target
done

exit





