#!/bin/bash

install-file()
{
    mkdir -p `dirname $2`
    ln -sfv $(pwd)/$1 $2
}

# neovim
ln -sfvT $(pwd)/nvim ~/.config/nvim
mkdir -pv nvim/{colors,autoload}
ln -sf $(pwd)/third_party/vim-monokai/colors/monokai.vim nvim/colors
ln -sf $(pwd)/third_party/vim-plug/plug.vim nvim/autoload

mkdir -pv ~/.config/ranger
for f in `ls rangerconf`
do
    ln -sfv $(pwd)/rangerconf/$f ~/.config/ranger/
done

ln -sfvT $(pwd)/mutt/ ~/.mutt
ln -sfvT $(pwd)/polybar/ ~/.config/polybar

ln -sfvT $(pwd)/zsh ~/.zsh
ln -sfvT $(pwd)/third_party/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ~/.zsh/zsh-syntax-highlighting.zsh
ln -sfvT $(pwd)/third_party/z/z.sh ~/.zsh/z.sh

gpg -d vdirsyncerconfig.gpg > vdirsyncerconfig
install-file vdirsyncerconfig ~/.vdirsyncer/config

install-file Xresources ~/.Xresources
install-file bin/currentlyplayed ~/bin/currentlyplayed
install-file bin/git-remotify ~/bin/git-remotify
install-file bin/i3exit ~/bin/i3exit
install-file bin/i3status-feeder.pl ~/bin/i3status-feeder.pl
install-file bin/mpcctl ~/bin/mpcctl
install-file bin/mpdhosttoggle ~/bin/mpdhosttoggle
install-file bin/mpvctl ~/bin/mpvctl
install-file bin/office ~/bin/office
install-file dunstrc ~/.config/dunst/dunstrc
install-file gitconfig ~/.gitconfig
install-file gpg-agent.conf ~/.gnupg/gpg-agent.conf
install-file i3config ~/.config/i3/config
install-file khalconfig ~/.config/khal/config
install-file liquidpromptrc ~/.config/liquidpromptrc
install-file mailcap ~/.mailcap
install-file mpv_config ~/.mpv/config
install-file offlineimap/offlineimap.py ~/.offlineimap.py
install-file offlineimap/offlineimaprc ~/.offlineimaprc
install-file qutebrowser.conf ~/.config/qutebrowser/qutebrowser.conf
install-file taskrc ~/.taskrc
install-file tmuxconf ~/.tmux.conf
install-file xinitrc ~/.xinitrc
install-file zshrc ~/.zshrc
