#!/bin/zsh

s3=""
s2=""
s1=""

if (ip addr | grep inet6 | grep global > /dev/null)
then
    ipv6=""
else
    ipv6=" "
fi

if ( ip link | grep enp0s25 | grep "state UP" > /dev/null )
then
    eth=""
else
    eth=" "
fi

if ( ip link | grep wlp3s0 | grep "state UP" > /dev/null )
then
    wlan=""
else
    wlan=" "
fi

echo "${ipv6} ${wlan} ${eth}"
