#!/bin/zsh

ac=$(cat /sys/class/power_supply/AC/online)
capa=$(cat /sys/class/power_supply/BAT0/capacity)

#
# check power levels
# 0: 0-15%
# 1: 16-35%
# 2: 35-65%
# 3: 66-85%
# 4: 86-100%
if [ "$capa" -lt "16" ]
then
    sym=""
elif [ "$capa" -lt "36" ]
then
    sym=""
elif [ "$capa" -lt "66" ]
then
    sym=""
elif [ "$capa" -lt "86" ] 
then
    sym=""
else
    sym=""
fi

# change to charging symbol if necessary, do not disturb coloring of bottom
if [ $ac -eq 1 ]
then
    sym=""
fi

echo "${sym} ${capa}%"
