#!/bin/zsh

mailnew=""
mailflagged=""
f="#dfdfdf"
f2="#555"
newmailnumber=$(notmuch count -- tag:unread)
flaggedmailnumber=$(notmuch count -- tag:flagged)

str=""

if [[ $newmailnumber -gt 0 ]]
then
    str="%{F${f2}} ${mailnew}%{F${f}} ${newmailnumber} "
fi

if [[ $flaggedmailnumber -gt 0 ]]
then
    str="${str}%{F${f2}} ${mailflagged}%{F${f}} ${flaggedmailnumber} "
fi

echo -n "%{F#555}$str"
