#!/bin/zsh

mailnew=""
mailflagged=""
f="#dfdfdf"
f2="#555"
newmailnumber=`find ~/mail -type f | grep '/INBOX[^\/]*/new/' | wc -l`
flaggedmailnumber=`find ~/mail -type f | grep '/INBOX.*,[A-Z]*F[A-Z]*$' | wc -l`

str=""

if [[ $newmailnumber -gt 0 ]]
then
    str="%{F${f2}} ${mailnew}%{F${f}} ${newmailnumber} "
fi

if [[ $flaggedmailnumber -gt 0 ]]
then
    str="${str}%{F${f2}} ${mailflagged}%{F${f}} ${flaggedmailnumber} "
fi

echo -n $str
