#!/bin/zsh

source ${HOME}/.config/mpd/mpdhost

# check if mpc is running and playlist not empty
if ( mpc 2>&1 > /dev/null )
then
    out=$(mpc 2>/dev/null)
    if ( echo $out | grep -e "^\[paused\]\|\[playing\]" 2>&1 > /dev/null )
    then
        currentsong=$(mpc current 2>/dev/null | /home/max/.config/polybar/shorten.pl )
        
        if (echo $out | grep "^\[playing\]" 2>&1 > /dev/null )
        then
            playpause=""
            fgcolor="#dfdfdf"
        else
            playpause=""
            fgcolor="#555"
        fi

        flags=""
        if (echo $out | grep "repeat: on" 2>&1 > /dev/null )
        then
            flags="${flags} "
        fi
        if (echo $out | grep "random: on" 2>&1 > /dev/null )
        then
            flags="${flags} "
        fi
        if (echo $out | grep "single: on" 2>&1 > /dev/null )
        then
            flags="${flags} "
        fi
        if (echo $out | grep "consume: on" 2>&1 > /dev/null )
        then
            flags="${flags} "
        fi

        echo "%{F${fgcolor}} ${playpause}  ${currentsong}  ${flags} "
        
    else
        exit 1
    fi
else
    exit 1
fi
