#!/usr/bin/env python3

import sys
import mpd

client = mpd.MPDClient(use_unicode=True)
client.connect("localhost", 6600)

status = client.status()

if status['state'] == 'stop':
    print('%{U#0000}', end='')  # otherwise polybar won't clear
    sys.exit()

cursong = client.currentsong()

fgcolor = "#dfdfdf" if status['state'] == 'play' else "#555"

flags = " "
if status['repeat'] == "1":
    flags += " "
if status['random'] == "1":
    flags += " "
if status['single'] == "1":
    flags += "1 "
if status['consume'] == "1":
    flags += " "

title = cursong['title']

print("%{F" + fgcolor + "} "+ title+flags, end='')
