#!/bin/zsh

f="#999"
f2="#333"
s3=""
s2=""
s1=""

default="%{F${f2}}"

if (ip addr | grep inet6 | grep global > /dev/null)
then
    ipv6="%{F${f}}"
else
    ipv6=$default
fi

if ( ip link | grep enp3s0f1 | grep "state UP" > /dev/null )
then
    eth="%{F${f}}"
else
    eth=$default
fi

if ( ip link | grep wlp2s0 | grep "state UP" > /dev/null )
then
    wlan="%{F${f}}"
else
    wlan=$default
fi

echo "${ipv6} ${s1} ${wlan} ${s3} ${eth} ${s2} "
