#!/bin/zsh

# COUNT TASKS, ORDERED BY THEIR URGENCY/DUE DATE

overdue=$(task "(+OVERDUE and urg < 15)" count)
today=$(task "(+TODAY and -OVERDUE and urg < 15)" count)
tomorrow=$(task "(+TOMORROW and urg < 15)" count)
week=$(task "(due.before=monday and due.after:tomorrow+24h and +DUE and urg < 15)" count)
important=$(task "urg >= 15 (+DUE or +OVERDUE)" count)
someday=$(task "(+PENDING and due='' and urg < 15)" count)

col_urgent="#f02020"
col_overdue="#f08020"
col_today="#f0f020"
col_tomorrow="#c0f020"
col_week="#40f020"
col_someday="#20d0f0"

f="#dfdfdf"
f2="#555"

sym_urgent=" "
sym_overdue=" "
sym_today=" "
sym_tomorrow=" "
sym_week=" "
sym_someday=" "

str=""

if [ "$important" -gt "0" ]
then
    str="${str}%{F${f2}}%{u${col_urgent}} ${sym_urgent}%{F${f}}${important} "
fi
if [ "$overdue" -gt "0" ]
then
    str="${str}%{F${f2}}%{u${col_overdue}} ${sym_overdue}%{F${f}}${overdue} "
fi
if [ "$today" -gt "0" ]
then
    str="${str}%{F${f2}}%{u${col_today}} ${sym_today}%{F${f}}${today} "
fi
if [ "$tomorrow" -gt "0" ]
then
    str="${str}%{F${f2}}%{u${col_tomorrow}} ${sym_tomorrow}%{F${f}}${tomorrow} "
fi
if [ "$week" -gt "0" ]
then
    str="${str}%{F${f2}}%{u${col_week}} ${sym_week}%{F${f}}${week} "
fi
if [ "$someday" -gt "0" ]
then
    str="${str}%{F${f2}}%{u${col_someday}} ${sym_someday}%{F${f}}${someday} "
fi

echo ${str}
