#!/bin/zsh

# COUNT TASKS, ORDERED BY THEIR URGENCY/DUE DATE

overdue=$(task "(+OVERDUE and urg < 15)" count 2>/dev/null)
today=$(task "(+TODAY and -OVERDUE and urg < 15)" count 2>/dev/null)
tomorrow=$(task "(+TOMORROW and urg < 15)" count 2>/dev/null)
week=$(task "(due.before=monday and due.after:tomorrow+24h and +DUE and urg < 15)" count 2>/dev/null)
important=$(task "urg >= 15 (+DUE or +OVERDUE or +READY)" count 2>/dev/null)
someday=$(task "(+PENDING and due='' and urg < 15)" count 2>/dev/null)

f="#dfdfdf"
orange="#ebab8b"
red="#bf616a"
f2="#555"

sym_urgent=" "
sym_overdue=" "
sym_today=" "
sym_tomorrow=" "
sym_week=" "
sym_someday=" "

str=""

if [ "$important" -gt "0" ]
then
    str="${str}%{F${red}} ${sym_urgent}%{F${red}}${important} "
fi
if [ "$overdue" -gt "0" ]
then
    str="${str}%{F${orange}} ${sym_overdue}%{F${orange}}${overdue} "
fi
if [ "$today" -gt "0" ]
then
    str="${str}%{F${f2}} ${sym_today}%{F${f}}${today} "
fi
if [ "$tomorrow" -gt "0" ]
then
    str="${str}%{F${f2}} ${sym_tomorrow}%{F${f}}${tomorrow} "
fi
if [ "$week" -gt "0" ]
then
    str="${str}%{F${f2}} ${sym_week}%{F${f}}${week} "
fi
if [ "$someday" -gt "0" ]
then
    str="${str}%{F${f2}} ${sym_someday}%{F${f}}${someday} "
fi

echo ${str}
